### PR TITLE
Feature/166/fix shared parameters

### LINKED ISSUE #166: In certain VxWorks when using publisher and subscriber in the same machine the -noPrint parameter is shared
**Description**

In certain VxWorks when using publisher and subscriber in the same machine the -noPrint parameter is shared

**How to Reproduce**

**Expected behavior**

**TODO**:
- [x] Support for C++ Traditional
- [x] First CR [Code Review]()
- [x] Support for C++ Modern
- [x] Automatic install testing
- [x] Documentation
- [ ] Full [Code Review]()
- [ ] Final Merge into master

### PR DESCRIPTION
**Pull request by salvacorts**
This pull request is coming from the issue #166 . When the pull request is merged into "master" the issue will be closed and fixed #166

### CODE REVIEW

**Comment by salvacorts** [comment]
Since VxWorks loads the same shared object, some addresses, like static class members, are shared across instances of the program within the same machine.

I have removed those static members by making them instance members. I think it would be worth having a look at other potentially problematic static variables; so far I have took care of `showCpu` (*cpu* param), `subID` (*sidMultiSubTest* param) and `printIntervals` (noPrint param), but there are other static variables like `perftest_cpp::INITIALIZE_SIZE` for example that I don't know if they are problematic in this context.

This is an screenshot of two perftest instances running in the same VxWorks machine, one with noPrint parameter (the subscriber, right), and one without (the publisher, left).
Screenshot from 2019-05-24 11-19-41

File: srcCpp/Infrastructure_common.h [hunk 1]
```diff
@@ -14,42 +14,31 @@
   #include "Infrastructure_pro.h"
 #endif
 
+#ifdef RTI_VXWORKS
```
Comment (javmorcas) [inline srcCpp/Infrastructure_common.h]: I think we might not need this if we make nddsUtility:sleep() work properly in VxWorks (this belongs to the alarm issue though).

File: srcCpp/Infrastructure_pro.cxx [hunk 2]
```diff
@@ -5,6 +5,19 @@
 
 #include "Infrastructure_pro.h"
 
+// Since std::to_string is not defined in c++98
```
Comment (javmorcas) [inline srcCpp/Infrastructure_pro.cxx]: If the comment uses more than 1 line:

/*
 * line 1
 * line 2
 */

File: srcCpp/Infrastructure_pro.cxx [hunk 3]
```diff
@@ -5,6 +5,19 @@
...
+// we will define it here for VxWorks
+#ifdef RTI_VXWORKS
```
Comment (javmorcas) [inline srcCpp/Infrastructure_pro.cxx]: I think this might be use as well for Micro, i would move it to infrastructure_common, what do you think?

File: srcCpp/Infrastructure_pro.h [hunk 4]
```diff
@@ -16,6 +16,10 @@
   #include "PerftestSecurity.h"
 #endif
 
+#ifdef RTI_VXWORKS
```
Comment (javmorcas) [inline srcCpp/Infrastructure_pro.h]: Same as previous comment

File: srcCpp/Infrastructure_common.h (hunk 1 above)
Comment (salvacorts) [reply srcCpp/Infrastructure_common.h]: Done

File: srcCpp/Infrastructure_pro.cxx (hunk 2 above)
Comment (salvacorts) [reply srcCpp/Infrastructure_pro.cxx]: Done

File: srcCpp/Infrastructure_pro.cxx (hunk 3 above)
Comment (salvacorts) [reply srcCpp/Infrastructure_pro.cxx]: Sure, but for what I have seen so far,  `infrastructure_common.h` includes `infrastructure_[micro | pro].h` How will Micro access this then?

Comment (salvacorts) [reply srcCpp/Infrastructure_pro.cxx]: I have tried to move it to `Infrastructure_common.cxx` and it has failed compiling

**Comment by salvacorts** [comment]
You should be able to merge it now Javi
