### PR TITLE
Initializing message memory to zero. 

### LINKED ISSUE #348: The test payload memory is not initialized just reserved.
**Description**
The `message.data` that is the payload content of the samples and the `announcement_msg.data` is reserved but never initialized to zeros.

This has not any impact on performance but could lead to some incorrect valgrind reports as "conditional jumps based on a non-initialized data".

**TODO**:
- [ ] Support for C++ Traditional
- [ ] First CR [Code Review]()
- [ ] Support for C++ Modern
- [ ] Support for Java
- [ ] Support for CS
- [ ] Automatic install testing
- [ ] Documentation
- [ ] Full [Code Review]()
- [ ] Final Merge into master

### PR DESCRIPTION
**Pull request by alfonso-soto**
This pull request is coming from the issue #348 . When the pull request is merged into "master" the issue will be fixed #348

### CODE REVIEW

File: srcCpp/perftest_publisher.cxx [hunk 1]
```diff
@@ -1910,6 +1911,9 @@ int perftest_cpp::Publisher()
         message.data = new char[(std::max)
                 ((int)_PM.get<unsigned long long>("dataLen"),
                 (int)LENGTH_CHANGED_SIZE)];
+        memset (message.data,0,(std::max)
```
Comment (javmorcas) [inline srcCpp/perftest_publisher.cxx:1914]: @alfonso-soto Remove space after memset.

**Comment by javmorcas** [comment]
I think this is fine. Can you check if we need to do the same in C++03? Also, add the documentation changes.

**Review by javmorcas — APPROVED** [review]
