### PR TITLE
Compilation error in Certain VxWorks #93

### LINKED ISSUE #93: Compilation error in Certain VxWorks
**Description**

In certain versions of VxWorks we don't have access to `sys/time.h`, therefore we fail at compilation time when doing the import.

**TODO**:
- [x] Support for C++ Traditional
- [x] Support for C++ Modern
- [ ] Pass [Code Review](https://github.com/rticommunity/rtiperftest/pull/95)
- [ ] Documentation
- [ ] Pull Request #issueNumber
- [ ] Final Merge into master

### PR DESCRIPTION
**Pull request by javmorcas**
This pull request is coming from the issue #93. When the pull request is merged into "master" the issue will be closed #93.

### CODE REVIEW

File: srcCpp/perftest_cpp.h [hunk 1]
```diff
@@ -18,8 +18,9 @@
 
 #ifdef RTI_WIN32
   #include <windows.h>
-#else
+#elif defined(RTI_VXWORKS)
```
Comment (softwarejimenez) [inline srcCpp/perftest_cpp.h]: Correct me if I am wrong. Are you including <sys/time.h> if not RTI_WIN32 and RTI_VXWORKS?

Should it be?
```
#elif !defined(RTI_VXWORKS)
```
